export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const FETCH_FILTERS_PENDING = 'FETCH_FILTERS_PENDING';
export const FETCH_FILTERS_SUCCESS = 'FETCH_FILTERS_SUCCESS';
export const FETCH_FILTERS_ERROR = 'FETCH_FILTERS_ERROR';

export const APPLY_FILTER = 'APPLY FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const LIKE_PRODUCT = 'LIKE_PRODUCT';
export const RATE_PRODUCT = 'RATE_PRODUCT';

export const FETCH_RECOMMENDATIONS_PENDING = 'FETCH_RECOMMENDATIONS_PENDING';
export const FETCH_RECOMMENDATIONS_SUCCESS = 'FETCH_RECOMMENDATIONS_SUCCESS';
export const FETCH_RECOMMENDATIONS_ERROR = 'FETCH_RECOMMENDATIONS_ERROR';